- README.md
Added style guide and link to live design mocks
> Added design docs

- _includes/header.html
> Add feed header to pages

- _config.yml
> Enable redirect and sitemap plugins

- _includes/head.html
- _includes/header.html
> Move into header

- _data/faq.yml
- operator.md
Depends on #5  for relocation to proper folder
> WIP: Add Operator to FAQ

- _data/faq.yml
> Document on ironic

- _posts/2019-06-30-first-post.markdown
- _posts/2019-07-30-second-post.markdown
- documentation.html
- index.html
Remove the sample post and the categories that them create to solve the travis errors
> Remove sample posts

- pages/privacy.md
Closes #3 
Asking Rusell for review
Will require additional PR for content linking
> Add privacy page

- index.html
Enable blog posts section on website
Closes #4
> Reenable blog posts

- _posts/2019-04-30-Metal-Kubed-Baremetal-Provisioning-for-Kubernetes.md
- index.html
> Convert post from russellb for metal3 site

- _layouts/post.html
- _sass/_global.scss
- blog/categories.html
> issue fixes

- _config.yml
- _includes/head.html
- _includes/metas-ogp.html
> Add tags for OGP

- _includes/blog-aside.html
- _includes/metas-ogp.html
- _includes/related-entries.html
- _layouts/post.html
> fixes opengraph bug

- _includes/metas-ogp.html
Defines type only on 'articles' removes trailing code since #59
> Include type only for articles

- _includes/head.html
- _sass/_type.scss
> updates css import

- blog/index.html
> Make title clickable

- _includes/head.html
- _includes/metas-ogp.html
> normalizing meta tags closes #78

- _layouts/post.html
> Slugify categories to ensure that whatever the case, are shown properly

- Gemfile
- _config.yml
- _includes/head.html
- assets/css/pygments.css
Based on https://frankindev.com/2017/03/18/syntax-highlight-with-rouge-in-jekyll/ details and http://pygments.org/demo/6350479/?style=manni stylesheet
Closes #50
> Add pygments to code hilighting

- _sass/_global.scss
- blog/index.html
closes #85
also updates pagination block to only show when 5 posts are present. We could probably bump this number to ten @dhellmann @iranzo WDYT?
> updates pagination, styles tables

- _includes/try-it.md
to reflect change in Metal3-dev-env : https://github.com/metal3-io/metal3-dev-env/pull/56
> Change 01_install_requirements.sh to 01_prepare_host.sh

- _includes/privacy-statement.md
Shows heading as it should be for privacy page
> Fix heading levels

- _config.yml
- _includes/head.html
We should use Adobe DTM for analytics as standard
> Remove GA code

- _includes/try-it.md
For when https://github.com/metal3-io/metal3-dev-env/pull/68 is merged
> Update docs for Ironic

- _includes/try-it.md
Docs that go along with https://github.com/metal3-io/metal3-dev-env/pull/82
> Update docs to just use clouds.yaml in metal3-dev-env repo

- _includes/try-it.md
This adds some explanations on the options to configure the metal3 dev env
Table preview at: https://deploy-preview-104--metal3.netlify.com/try-it.html
> Add a table explaining metal3-dev-env configuration options

- _includes/docs.md
- _posts/2019-12-04-Introducing_metal3_kubernetes_native_bare_metal_host_management.md
Blogpost about the Metal3 talk and video from the KubeCon NA 2019
/cc @russellb 
/cc @dhellmann 
Publication date is set to 2019-12-04 for having some time to review.
> Metal3 kubecon 2k19 blogpost

- _includes/related-entries.html
- _sass/_subpage.scss
> fixes recent entries spacing

- OWNERS
> Modify OWNERS to define labels

- _includes/metas-ogp.html
Fix for twitter and linkedin opengraph
> Use full URL for og image

- _posts/2019-12-04-Introducing_metal3_kubernetes_native_bare_metal_host_management.md
Add video miniature to asciinema.org videos
> Add miniatures to screen videos

- _includes/footer.html
- _includes/head.html
Update to latest code for DTM -> DPAL transition for analytics
> Update to latest code for DTM -> DPAL transition for analytics

- _includes/docs.md
- _posts/2020-01-20-metal3_deploy_kubernetes_on_bare_metal.md
Signed-off-by: Pedro Ibáñez <pedro@redhat.com>
Blog post about the video of Yolanda Robla, a presentation about Metal3 made in the Shift Dev event in Croatia.
To publish during January 20th.
> yolanda's shift dev video blogpost

- community-resources.html
Link was not updated when the doc was relocated to project-infra, fixing
> Update link to relocated project-infra

- _includes/blog-aside.html
- _includes/docs.md
- _includes/metas-ogp.html
- _layouts/post.html
- index.html
> Add spacing in headers

- _includes/try-it.md
This PR adds the new environment variables which are introduced in 
PR#194(https://github.com/metal3-io/metal3-dev-env/pull/194)
> Add new environment variables

- _includes/try-it.md
Update try-it doc based on changes made in [PR#216](https://github.com/metal3-io/metal3-dev-env/pull/216).
> Update try-it.md based on merged PR#216

- .travis.yml
Use travis for generating webpage
> Generate pages via travis

- _config.yml
- _includes/header.html
- _layouts/search.html
- _sass/_autocomplete.scss
- _sass/_inputs.scss
- _sass/styles.scss
- assets/js/lunr.min.js
- search.html
Add search to website
Preview at: https://deploy-preview-141--metal3.netlify.com/
> Add search

- OWNERS
> Addalosada

- _includes/head.html
- _includes/header.html
- _layouts/post.html
- assets/js/photoswipe-page.js
Adds gallery support within article codes to show large images
> Add PhotoSwipe gallery support

- GUIDELINES.md
**What this PR does / why we need it**:
Document on how to use image display for big images
**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
> Fixes #
**Special notes for your reviewer**:
> Document how to use gallery

- _config.yml
- assets/js/copy.js
Signed-off-by: Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>
> Disable line numbers

- _includes/head.html
**What this PR does / why we need it**:
Review sitemap status on crawlers
> Add site verification

- README.md
Fixes container name to be metal3
> Fix container name

- Rakefile
Disable youtube links from linkchecker as it's giving false positives
> Ignore youtube links on linkchecker

- _includes/blog-aside.html
Use - for categories in blog-aside
> Use - for categories with spaces

- _layouts/search.html
Signed-off-by: Pedro Ibáñez <pedro@redhat.com>
fixing possible xss attack through the search results page
> fixing possible xss attack through the search results page

- try-it.md
Update try-it based on [#250](https://github.com/metal3-io/metal3-dev-env/pull/250) in Metal3-dev-env.
> Update try-it based on #250 in Metal3-dev-env

- try-it.md
Fix existing typos in ` try-it.md ` document
> Fix existing typos in try-it.md

- try-it.md
Update try-it.md based on the changes in Metal3-dev-env.
> Update quick-start page

- _posts/2020-02-18-metal3-dev-env-install-deep-dive.md
- _posts/2020-06-18-Metal3-dev-env-BareMetal-Cluster-Deployment.md
- try-it.md
There is a change in metal3-dev-env that needs to be reflected here : https://github.com/metal3-io/metal3-dev-env/pull/400
> Update variable CAPI_VERSION to CAPM3_VERSION

- _posts/2020-06-18-Metal3-dev-env-BareMetal-Cluster-Deployment.md
- try-it.md
https://github.com/metal3-io/metal3-dev-env/pull/403
> Reflect refactoring changes in metal3-dev-env

- try-it.md
Fixes [metal3-dev-env/issues/434](https://github.com/metal3-io/metal3-dev-env/issues/434)
> Add note regarding redeploying metal3-dev-env

- try-it.md
Update quick-start based on https://github.com/metal3-io/metal3-dev-env/pull/391.
> Update try-it.md with ironic-client

- _includes/footer.html
- _sass/_footer.scss
As requested on https://github.com/cncf/toc/issues/532
> footer: Add Linux Foundation footer

- _posts/2019-06-25-Metal3.md
- _posts/2020-06-18-Metal3-dev-env-BareMetal-Cluster-Deployment.md
Added demo video to compliment the blog post and a few other minor updates.
> Added video and some other minor updates

- .pre-commit-config.yaml
> build(precommit-config): updates precommit config to later modules

- .github/dependabot.yml
- .github/workflows/broken-link-check.yml
- .github/workflows/jekyll.yml
- .travis.yml
Removes travis and uses GHA for pushing the site
> Remove travis

- .github/workflows/jekyll.yml
> Fix web root

- try-it.md
Update the content of the try-it.md to be aligned with the current state of the metal3 project.
> Update the content of the try-it.md

- LICENSE
Per package.json, this project is licensed under MIT license. Make it explicit by adding MIT LICENSE to the root of the repository.
> LICENSE: add MIT license file

- documentation.html
There is no opening section tag on the documentation.html. I have added it. 
/assign @hroyrh
> added section opening tag

- .gitignore
- .pre-commit-config.yaml
- _posts/2023-05-05-Scaling_part_1.md
Add post about scalability. This is the first part in a series of blog posts and focuses on BMO test mode.
Also updates .gitignore and pre-commit config
> Post: Scaling part 1

- .yaspeller.json
- _posts/2020-02-18-metal3-dev-env-install-deep-dive.md
Fix spelling errors that are currently failing.
Related to #313
> fix currently failing words in spellcheck

- try-it.md
I noticed that the word "the" was repeated on two different instances. I have made the necessary correction.
> made a grammar correction

- _sass/_global.scss
- _sass/_homepage.scss
- index.html
Changed the position and style of the blog section
> Blog section update 

- _sass/_header.scss
- _sass/_variables.scss
- index.html
- Changed a bit of the content
- Removed the user-guide button
- Increased title font
- Changed bg-image to a lighter contrast
> Hero section update

- _sass/_header.scss
- index.html
fixed alignment on body and nav responsiveness
> Alignment fix

- index.html
Updated component titles with links
cc: @hroyrh
> Components update

- _sass/_header.scss
- _sass/_homepage.scss
- _sass/_type.scss
- index.html
Created a section for the goals and missions of Metal3
> Mission and goal section

- _includes/docs.md
- _includes/footer.html
- _includes/header.html
- community-resources.html
> Moved Documention content to Community resources

- try-it.md
Including:
- Some links fixed
- Added minimun disk size
- Updated the script paths
> Small updates to try it

- _includes/header.html
- _sass/_header.scss
While trying to make UI updates to the search bar on the metal3 website, i might have tampered with its functionality, the search functionality only worked on the mobile because of an id repetition, so i created a single id to get it back up again
cc: @hroyrh @elfosardo
> Search bar fix 

- _includes/footer.html
- _sass/_footer.scss
> Repostioned footer links for mobile

- _sass/_global.scss
- _sass/_subpage.scss
Removed coloured highlights from text in FAQs and blog page
cc: @Rozzii  @lentzi90
> Removed coloured highlights from text

- OWNERS
> Move iranzo to emetirus approvers

- _includes/footer.html
Closes: #353 
Removed twitter from footer as the twitter account is not seem active
> docs: removed twitter from footer

- _sass/_header.scss
- index.html
Also fix a repetition in the sub title
> Change title color to improve readability

- _includes/header.html
- community-resources.html
- index.html
Image paths were relative and this caused the website to look for the images in the wrong url. I changed the image paths it fixed the issue. Fixes #367
> :bug: Fix broken images

- documentation.html
- index.html
> Standardize metal3 pronunciation

- hack/spellcheck.sh
Bump spellcheck container from 8.3.2 to 8.9.0.
Make /workdir a variable.
> bump spellcheck to 8.9.0

- .lycheeignore
Link checker is giving some false positives. I suggest we add links to ignore file to avoid these false positives. 
Fixes: #527
Fixes: #528
> :seedling: Add more links to ignore file

- .github/workflows/broken-link-check.yml
Once a week produces the same results week after week. Once a month is often enough.
Also, reindent properly.
> run broken link checker periodic once a month

- OWNERS
- OWNERS_ALIASES
Move mquhuy and mboukhalfa to emeritu reviewers.
Thanks for all the contributions and reviews!
> move mquhuy and mboukhalfa to emeritus reviewers

- _posts/2020-06-18-Metal3-dev-env-BareMetal-Cluster-Deployment.md
> chore: fix broken link in dev env documentation
