metal3-io/metal3-io.github.io

_faqs/what-is-ironic.md

Ironic is an implementation detail, and doesn't need to be mentioned
on the home page in the FAQ.

remove faq describing ironic

---

_includes/docs.md
_posts/2019-11-07-Kubernetes-native_Infrastructure-Managed_Baremetal_with_Kubernetes_Operators_and_OpenStack_Ironic.md

Converts the media link to that event in a blogpost as discussed in #73 
Preview at: https://deploy-preview-106--metal3.netlify.com/blog/2019/11/07/kubernetes-native_infrastructure-managed_baremetal_with_kubernetes_operators_and_openstack_ironic

Video blogpost about the kni managed baremetal talk at Red Hat summit 2019

---

_includes/docs.md
_posts/2019-05-13-The_new_stack_Metal3_Uses_OpenStack_Ironic_for_Declarative_Bare_Metal_Kubernetes.md

Blogpost The_new_stack_Metal3_Uses_OpenStack_Ironic_for_Declarative_Bare_Metal_Kubernetes
Let's publish it next week (Monday 9th or Tuesday 10th is good, I'll ping you reviewers for that)
Signed-off-by: Pedro Ibáñez <pedro@redhat.com>

The new stack blogpost

---

README.md

Signed-off-by: Alberto Losada <alosadag@redhat.com>
Change README.md detailing how to run the web locally by running a container using podman instead of docker

Replace docker by podman when building the web locally

---

_includes/try-it.md

There were some changes in [provisioning/deprovisioning](https://github.com/metal3-io/metal3-dev-env/tree/master/scripts/v1alphaX) scripts introduced with [PR#229](https://github.com/metal3-io/metal3-dev-env/pull/229). This patchset updates try-it accordingly.

Update try-it based on PR#229 in metal3-dev-env

---

_layouts/post.html

Fixes links when keywords have spaces

Use - instead of spaces for links

---

_includes/docs.md
_posts/2020-03-05-CAPI_provider_renaming.md
try-it.md

That is related to https://github.com/metal3-io/metal3-dev-env/pull/239 and https://github.com/metal3-io/cluster-api-provider-baremetal/issues/267 .
It also adds a post about the renaming.

Rename CAPBM to CAPM3

---

try-it.md

The rename in #153 forgot to update one header, only updating a reference to it from the table of contents, leaving the change half-done.
Then, #160 (57679b1) reverted the half-done part (i.e. the header reference), so undoing the part of the change that was already done.
This updates both the header and its reference to reflect the rename from Cluster API Provider Baremetal to Cluster API Provider Metal3.

Rename header reference from CAPBM to CAPM3

---

_posts/2020-02-18-metal3-dev-env-install-deep-dive.md

This is just and update of the blog post "A detailed walkthrough of the Metal³ development environment" already published. I just replaced the links to the videos since they were moved from my personal account to the metal³ Youtube account.
Signed-off-by: Alberto Losada <alosadag@redhat.com>

Replace video links from my personal account to metal3 youtube account

---

Rakefile

Ignores 429 errors on pages like github, etc that shouldn't be either fail or succeed

Ignore 429 errors on html-proofer

---

.pre-commit-config.yaml
.yaspeller.json

Yaspeller got a PR merged so that it can be used directly.
This moves configuration to .yaspellerrc and makes pre-commit to check only markdown files in the commit

Point to yaspeller upstream repo for pre-commit plugin

---

try-it.md

Try-it documentation page has been updated with the required changes due to recent changes in [metal3-dev-env PR 264](https://github.com/metal3-io/metal3-dev-env/pull/264)
Basically this PR focuses on replacing CentOS 7 system and target cluster OS with CentOS 8.

Update try-it due to CentOS 8 replacement

---

try-it.md

I have updated the ssh_username to "metal3" wherever required, and this applies for all the image types.

Reflect the change of ssh username to metal3 for all images

---

OWNERS

Add Stephen and Maël, since both have reviewed content and are knowledgeable about the details needed to provide good reviews.
Also clean up the owners file
/cc @stbenjam @maelk

add stbenjam and maelk as approvers for blog posts

---

OWNERS

To  complement #183 : there have been some changes in the community team at RH and former website maintainers moved to another group.
For this change to work I should be part of the org (not there at the moment)

Update owners to reflect team changes

---

Gemfile
index.html

The current homepage side bar shows the whole list of blog posts under _"what's new?"_. This makes the page too long (and growing).
The PR limits that side bar's content to only the latest 3 blog posts.
Also adding `rake` to the Gemfile, which allows things like locally checking external links, e.g.
```sh
podman run --rm -i \
--name linkcheck -v $(pwd):/srv/jekyll:Z jekyll/jekyll:latest \
/bin/sh -c "bundle install && bundle exec rake links:test_external"
```

Limit the number of blog posts highligted in the home page

---

Rakefile
_posts/2019-06-25-Metal3.md

Removed section from `Metal3` blog post which had a broken link, since its no longer relevant. And ignored twitter urls so that ci-testing doesn't break.

fix broken link and ignore twitter 400 error during ci testing

---

_posts/2019-06-25-Metal3.md
try-it.md

Changed mentions of v1alpha3 to v1alpha4 after verifying the scripts still work. Also fixed minor typos and added a short section about using the `config_user.sh` file

 Update try-it guide to refer v1alpha4 instead of v1alpha3

---

try-it.md

Update the Try-it.md to include the changes from release v1beta1.
The session 2.5 Running custom CAPM3 is not finished, since the
make run command is deprecated.

📖 Update Try-it page based on the v1beta1 API

---

.pre-commit-config.yaml
Gemfile
README.md
_config.yml
documentation.html
index.html

- Bump blacken-docs version (it was failing for me with the old version)
- Add link to the new user-guide
- Update build status badge
- Fix spelling
- Add `webrick` gem as development dependency (it is needed for `jekyll
serve` for some versions of Jekyll)
- Remove duplicate config for highlighter

Misc fixes

---

.github/workflows/broken-link-check.yml
.github/workflows/jekyll.yml

Set top-level permissions to read, only allowing write where necessary.
Pin actions by a sha.

.github: secure github actions

---

.github/workflows/jekyll.yml

Jekyll has been unable to deploy pages for a while now, thanks to too tight permissions. This should fix the issue.

fix jekyll permissions

---

.github/workflows/jekyll.yml

Revert changes to Jekyll's permissions, and come back at them again when the deployment is working again.

revert jekyll permissions changes

---

.github/dependabot.yml

Add "npm" ecosystem to dependabot configuration. Use same default reviewers as Github actions.

add npm ecosystem to dependabot

---

SECURITY_CONTACTS
documentation.html
index.html

Our user-guide is now properly hosted at https://book.metal3.io/

update user-guide url

---

OWNERS

Files like `_header.scss` did not match the CSS pattern in owners due typo.
Noticed in PR #289 .

fix sass -> scss in owners

---

_includes/footer.html

#346 was opened before the pre-commit status check was added, so it wasn't properly checked. This PR fixes a trailing whitespace that was introduced as a consequence.

Fix trailing whitespace

---

.github/workflows/pre-commit.yml

Add default permissions, and also prevent it from running in forks, same as other workflows.
Pin two remaining actions to SHA digests.

improve pre-commit workflow

---

.github/dependabot.yml

Running dependabot daily is excessive. Change `daily` to `weekly` for NPM and `monthly` to GH actions. Security updates will ignore these schedules anyways.

run dependabot less often

---

.pre-commit-config.yaml
.yaspeller.json

We are using way too old yaspeller version, which caused issue #378

Update yaspeller to latest version

---

_posts/2024-01-18-How_to_run_Metal3_website_locally_with_Jekyll.md

This included #388 with the necessary fixes to make pre-commit happy.
Author: @SafeEHA <eemarabs@gmail.com>

add Salima's blog post on Jekyll

---

OWNERS

Remove all the filters, we're not really using them for anything. Same people basically everywhere anyways. Two changes proposed:
- add `kashifest` to reviewers
- move `matthewcarleton` to emeritus_approvers (from css filter approver)

simplify OWNERS

---

blog/index.html

Currently, if one is in page > 2 (for e.g. https://metal3.io/blog/page5/), and click on pagination "1", one will be sent to page {{ page - 1 }}, instead of page 1. This is to fix that error.

:bug:  Fix paginator error on blog first page

---

.github/workflows/broken-link-check.yml
.github/workflows/jekyll.yml

Don't run broken link checker nor deploy workflows on forks.

add if: repository check to workflows

---

OWNERS_ALIASES

This repository does not see much traffic so these changes are mainly based on contributions elsewhere (e.g. metal3-docs that has similar content).
Approvers as agreed over email. I also added some reviewers based on commits in this repo and presence in metal3-docs.
/cc @elfosardo @hroyrh

Add more approvers and reviewers

---

Makefile
README.md
hack/pre-commit.sh

The Makefile contains targets for linting for serving the website
locally.
This commit also adds a hack script for running pre-commit similar to
markdownlint, shellcheck and spellcheck. Now all of them can be run with
a simple `make lint` as long as podman or docker is available.
The README.md is also update to make use of the make serve command. The
image that was used in the readme no longer works with the versions we
are using.

Add Makefile for linting and serving

---

.github/workflows/broken-link-check.yml

There is no need to run it daily, especially with the amount of flakes it produces these days. I will replace this with better checker later on.

run broken link checker once a week

---

.github/dependabot.yml

Since the last update, we have introduced Prow blunderbuss for reviews, and also don't use the scope/commit message prefixes etc. We also want to give `ok-to-test` automatically now.

update dependabot config to match other repos

---

hack/spellcheck.sh

It contains some bug fixes since previous version v8.9.0.
No fixes to spellings needed.

update cspell spellchecker to v8.13.3

---

hack/spellcheck.sh

Since we're running the check in sh, it does not have globstar option to handle '**/*.md' properly. It only checked exactly one level deep markdown files. Spellcheck handles globs itself, so just adding quotes is enough to fix it.
In this repo, it only ignored top-level ones, which luckily do not have any spellcheck issues, so it is enough to just fix the glob.

fix spellcheck glob

---

.github/workflows/broken-link-check.yml
.lycheeignore

Current Broken-link-checker is not actually checking in the https://metal3.io/ webpage. It is causing a lot of flakes like this: 
https://github.com/metal3-io/metal3-io.github.io/issues/448 
https://github.com/metal3-io/metal3-io.github.io/issues/485 
In current link checker no URL is specified so it uses the default https://github.com/${{ github.repository }}{}. This means we are checking links in the site https://github.com/metal3-io/metal3-io.github.io instead of the intended https://metal3.io/ . To check all pages in a site we should serve a sitemap.xml as input to be checked. 
I also think workflow should move to use lychee
https://lychee.cli.rs/introduction/#check-all-links-on-a-website
https://github.com/lycheeverse/lychee-action
Lychee is better documented, has active maintainers …

🌱 Change link checker to lychee

---

.github/workflows/pr-gh-workflow-approve.yaml

Add PR GH workflow auto-reapprover from CAPM3. We have pre-commit here as workflow, and it needs to be manually re-approved now each time non-member pushes PR or updates PR.

add auto (re)approver workflow

---

_posts/2019-06-25-Metal3.md

Signed-off-by: lekaf974 <matthieu.evrin@gmail.com>
Fix #523

fix: openshift cluster-api controller machine broken link

---

.github/dependabot.yml

Group dependabot action bumps into one PR, like in other repos.

group dependabot action bumps into one pr

---

_posts/2024-05-30-Scaling_part_3.md

Fix broken link to CAPI's tilt documentation.
Fixes: #547

fix broken link to cluster-apis tilt doc

---

contribute.html

This PR:
- Updates the zoom link in the contribute.html
This commit is needed because now the community started to manage the zoom meeting via LFX Project Control Center and the old link is not relevant anymore.

update zoom link on contributor page
